{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/mms\",\"statusCode\":500,\"message\":\"Internal server error\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:22:11.427Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/auth\",\"statusCode\":500,\"message\":\"Internal server error\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:22:27.579Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/auth\",\"statusCode\":500,\"message\":\"Internal server error\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:25:05.268Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/auth\",\"statusCode\":500,\"message\":\"Internal server error\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:26:11.590Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/auth\",\"statusCode\":500,\"message\":\"Internal server error\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:27:56.316Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/auth\",\"statusCode\":500,\"message\":\"Internal server error\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:30:22.901Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/mms\",\"statusCode\":500,\"message\":\"Internal server error\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:30:27.397Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/mms\",\"statusCode\":500,\"message\":\"Service communication error. /v1/mms currently unreachable\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:36:48.021Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/mms\",\"statusCode\":500,\"message\":\"Service communication error. /v1/mms currently unreachable\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:40:39.319Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/auth\",\"statusCode\":500,\"message\":\"Service communication error. /v1/auth currently unreachable\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:41:08.197Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/auth\",\"statusCode\":500,\"message\":\"Service communication error. /v1/auth currently unreachable\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:42:57.899Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/mms\",\"statusCode\":500,\"message\":\"Service communication error. /v1/mms currently unreachable\",\"stack\":\"AggregateError\\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\\n    at RedirectableRequest.emit (node:events:507:28)\\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\\n    at ClientRequest.emit (node:events:507:28)\\n    at emitErrorEvent (node:_http_client:104:11)\\n    at Socket.socketErrorListener (node:_http_client:518:5)\\n    at Socket.emit (node:events:507:28)\\n    at emitErrorNT (node:internal/streams/destroy:170:8)\\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"AggregateError\n    at AxiosError.AxiosError.from (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:507:28)\n    at eventHandlers.<computed> (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:507:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:507:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (/home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:43:05.221Z"}
{"level":"error","message":"{\"method\":\"GET\",\"url\":\"/v1/mms\",\"statusCode\":500,\"message\":\"Internal server error\",\"stack\":\"TypeError: Cannot destructure property 'serviceUrl' of 'this.services[service]' as it is undefined.\\n    at RouteController.forward (/home/doruk/Enterprise/ShelfWise/api-gateway/src/routes/route.controller.ts:41:13)\\n    at /home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/@nestjs/core/router/router-execution-context.js:38:29\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}","stack":"TypeError: Cannot destructure property 'serviceUrl' of 'this.services[service]' as it is undefined.\n    at RouteController.forward (/home/doruk/Enterprise/ShelfWise/api-gateway/src/routes/route.controller.ts:41:13)\n    at /home/doruk/Enterprise/ShelfWise/api-gateway/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-05-19T09:44:17.437Z"}
